### PR TITLE
Fixes #352

### LINKED ISSUE #352: Remove From Disk doesn't work
The remove from disk option does not seem to work.
When I click the button, nothing happens.

### PR DESCRIPTION
**Pull request by Magentaize**

### CODE REVIEW

**Comment by digimezzo** [comment]
I broke the pull request because I changed the Utilities library from my side. I'll try a manual merge.

**Comment by digimezzo** [comment]
I give up :) I just fail at fixing this merge conflict. Could you remove Digimezzo.Utilities.dll from the full request? That file is already up to date in the master branch. If you remove that file, I should be able to merge this pull request.

**Comment by Magentaize** [comment]
That is really surprising and I have resolved the conflict now. :)

**Comment by digimezzo** [comment]
Thanks! Well it was my fault :) I updated the utilities dll from my side too. Our changes conflicted.

**Pull request merged**
