### PR TITLE
XButton1 & 2 can be used for playing previous or next track.

### PR DESCRIPTION
**Pull request by filoe**
See #267.

### CODE REVIEW

**Comment by Riajyuu** [comment]
This can work. But what if user edit key preferences in mouse driver program?

**Comment by filoe** [comment]
Well, make a suggestion on how to handle that.

**Comment by Riajyuu** [comment]
Sorry. I don't know much about C# programming. I'm simply point out such possibilities. But I believe if there can be any solution of this case, it can be only fetching value data from Registry. Correct me if I'm wrong.

**Comment by digimezzo** [comment]
Thanks!

**Pull request merged**
