### PR TITLE
Fixes #51 :Bluetooth headset play/pause button not detected

### LINKED ISSUE #51: Bluetooth headset play/pause button not detected
But I am having a problem with my Philips SHB7000 wireless headset and Dopamine. When using my headset's media keys, Next and Previous works as expected but Play/Pause doesn't work. Its not picked up by your Keyboardtest. Groove Music has no problem with my headset.

### PR DESCRIPTION
**Pull request by gjhwssg**
Fixes #51 :Bluetooth headset play/pause button not detected

### CODE REVIEW

**Comment by digimezzo** [comment]
Hi. Thanks a lot! You were able to test this with a Bluetooth headset? I don't have a Bluetooth headset to test with, so I'd like your confirmation before pulling it in.

**Comment by gjhwssg** [comment]
It is work well on my Sony SBH70 Bluetooth headset.

**Comment by gjhwssg** [comment]
Do not you have a Philips SHB7000 wireless headset？

**Comment by digimezzo** [comment]
No, I had a wired Philips headset. Thanks for confirming. I'll pull your code in tonight.

**Comment by digimezzo** [comment]
It seems that with this modification, Dopamine remains running in the background when the main window is closed. I can't pinpoint what is causing this. Do you have an idea?

Edit:

It seems that if I move this bit of code

`this.win32InputService.UnhookKeyboard();`

 from Shell_Closing() to Shell_Closed(), that the application closes properly. I'm not sure why.

**Comment by gjhwssg** [comment]
I found this bug occurs in debug mode,  release not.
I do not know why either.😅

**Comment by digimezzo** [comment]
No problem. My above workaround seems to help for that issue.

Someone discovered another issue: on some keyboards, the media keys don't work anymore since applying this code. I think I might have to combine your APPCOMMAND code with a regular SetWindowsHookEx() to make sure ALL media keys are catched. What do you think? Do you have experience with that?

**Comment by gjhwssg** [comment]
OK.
However two hook  may be triggered simultaneously on some keyboards.Do you have any idea?
ps: my keyboards is work well.

**Comment by digimezzo** [comment]
I was thinking this too (that 2 hooks might be triggered simultaneously). My keyboard works too with your code. So I'm not sure yet what causes it to break on some other people's keyboard. I think I'll do some tests tonight with multiple hooks and see what happens.

**Comment by gjhwssg** [comment]
OK.
The worst situation,maybe we can add a toggle button on the settings screen?

**Comment by digimezzo** [comment]
OK, I tried it out and the hooks indeed interfere with each other. I added an ugly workaround: a timer that prevents the second hook from firing the events during the first 250 ms that the first hook got an event.
It seems to work fine at first sight. Could you try it out with your headset (latest code on github has the changes, build 708 on [Digimezzo ](http://www.digimezzo.com/content/software/dopamine/previews/)has the changes also)

**Comment by gjhwssg** [comment]
Build 708 is work well on my bluetooth headset.

**Comment by digimezzo** [comment]
Excellent! Thanks for confirming. I have confirmation of the other user with media key issues that build 708 also fixes it for him.

**Pull request merged**
