### PR TITLE
Using CSCore Codec factory to allow a broader range of files to be played

### PR DESCRIPTION
**Pull request by tstavropoulos**
With this trivial change, the responsibility of selecting the proper codec is exported to the CSCore CodecFactory.  While testing out Dopamine, I encountered an exception while trying to play a `*.flac` file, took a look, and saw that the file formats that would play were very constrained relative to what CSCore *can* play, entirely due to the fact that the proper codecs weren't being used.

### CODE REVIEW

**Comment by digimezzo** [comment]
I'll have to look at this in more detail. I think CodecFactory doesn't support OGG and OPUS. CodecFactory only plays what is supported by MediaFoundation.

**Comment by tstavropoulos** [comment]
Actually, you can register new handlers with the codec factory (as long as you're not relying on some internal file metadata to determine which codec to use).  In my own WPF music player project, also using CSCore, I did just this.  During application initialization, you can call:

```csharp
CodecFactory.Instance.Register("ogg-vorbis", new CodecFactoryEntry(s => new NVorbisSource(s).ToWaveSource(), ".ogg"));
```

And use something like [NVorbis](https://github.com/ioctlLR/NVorbis) or roll your own.

**Comment by tstavropoulos** [comment]
Take a look at the `CodecFactory` constructor [here](https://github.com/filoe/cscore/blob/master/CSCore/Codecs/CodecFactory.cs) to see its registration of the existing codecs.  Notice that it uses a custom, non-MediaFoundation codec for at the very least the FLAC codec.

**Comment by digimezzo** [comment]
This was done in db451f744f5d9232d666976d6e7239d7cb960eff, where I removed FFMpeg completely. Actually, this was the way things were done before I added FFMpeg.

**Pull request closed without merging**
