### PR TITLE
Enhances #164

### PR DESCRIPTION
**Pull request by Magentaize**

### CODE REVIEW

**Comment by digimezzo** [comment]
Could you inverse responsibilities in this change? The repositories should not have dependencies on the services. So you should put the Watcher logic in IndexingService, and reference FolderRepository in IndexingService.
Thanks!

**Comment by Magentaize** [comment]
Actually, I cannot decide the location where I should put these code. I'll move them since you point out it.

**Comment by digimezzo** [comment]
I tried to separate the software into layers. The service layer contains all the services. These services can be referenced in Views and ViewModels, and in some specific cases, in other services (but I try to limit that, because I think it might be a bad design choice).

The data layer contains everything that is database access (for example, the repositories).
The repository classes are helper classes to access the database. They should always be in the bottom layer, closest to the data base. Here is a quick and dirty drawing of what I try to respect :)

image

**Comment by Magentaize** [comment]
So clearly! Now I have got it, in fact, I cannot distinguish IndexingService, CollectionService and Repositorise before. I try move the logic into IndexingService, the FolderRepository indeed not need any services. 
Thanks for your drawing.

**Comment by Magentaize** [comment]
@digimezzo I have move the logic into IndexingService.

**Comment by digimezzo** [comment]
That looks good! Thanks!

**Pull request merged**
