### PR TITLE
Enhancement: blur style spectrum analyzer#222

### PR DESCRIPTION
**Pull request by Magentaize**

### CODE REVIEW

**Comment by digimezzo** [comment]
I've merged this to a separate branch to test out the changes. Ultimately, I'd like to provide an option to switch between both spectrum analyzers. I'm not yet sure it will be possible.
It seems you also added a new version of WPFSoundVisualizationLib. What were the changes?

**Comment by Magentaize** [comment]
I also like to add an option to switch these two styles, however many
layout problems should be considered.
Talking about the new version of SoundVisualizationLib, it's my modified
version which tweaks the flatness of bar animation.Actually, this library
hasn't been updated for a long time.

**Comment by digimezzo** [comment]
I played with your implementation, and it is really nice. I think I can add an option to have 2 looks for the spectrum analyzer. Just by playing with BlurRadius, SpectrumBarCount, SpectrumBarSpacing and SpectrumPanelHeight on your implementation, I got this look. Which is very similar to the original spectrum. Only the spacing between the 2 channels is too large. But I guess that can easily be corrected.

spectrum

You also got stereo spectrum to work it seems. Would you mind sharing the modified visualizationlib? I'm curious how you improved the animations. Do you think we could put some fork on GitHub?

Thanks!

**Comment by Magentaize** [comment]
Great!I can not wait to see the user's and my friends' responses.
About this visualizationlib, as you see, I removed the PeakDotHeight
property because I found the PeakDot has a more gentle animation which
using arithmetic mean so I replaced the original Bar height with the
PeakDot height. However, I think it's not enough, once I have found a
better algorithm, I'll share it on github.

**Comment by digimezzo** [comment]
I've merged your implementation with the master branch. Also removed WPFVisualizationLib.dll and added a simplified version of SpectrumAnalyzer to the Dopamine code under Dopamine.Common.Audio. I thin k the MIT license allows this (I've retained the author's license in the code and Dopamine installer). This allows me to keep track of tweaks needed for Dopamine. And also allows me to add more tweaks to allow the 2 types of Spectrum analyzers.

I noticed that after pausing a track, the spectrum analyzer doesn't appear any more. I haven't found the cause yet. Do you know what causes it?

**Comment by Magentaize** [comment]
When property IsPlaying of IPlayer has changed, the event  PropertyChange of  WrapperSpectrumPlayer dosen't be invoked.
Sorry, I missed it.

**Comment by Magentaize** [comment]
By the way, I have added a smoother animation to ToggleSwitch in WPFControls.

**Comment by digimezzo** [comment]
Thanks! :) 
I'm almost finished with the spectrum analyzer selection. I'm adding possibility to switch between the "old" spectrum style and your new style :)

**Comment by digimezzo** [comment]
The master branch now contains the combobox to switch between spectrum analyzers. I didn't have much inspiration for their names :)

image

**Pull request merged**
