### PR TITLE
Fixes #30

### LINKED ISSUE #30: Remove from alt+tab when minimized to tray
When Dopamine sits in tray and has no opened windows, it still shows in Alt+Tab.

### PR DESCRIPTION
**Pull request by Magentaize**

### CODE REVIEW

**Comment by digimezzo** [comment]
Thanks! I just reviewed it, but fixed #30 differently in commit ba277dbd7a51936a74fce35fe4d6446a25cb5623, so I'll close this pull request. There was already a function HideWindowFromAltTab(Window win) in Dopamine.Core.Utils.WindowUtils, and I chose to reuse that one. I wish I could merge selectively from your pull request, as your changes to some of the files have been applied in my commit. But doing that in Git would seem to cost more time that just adding them manually.

**Comment by Magentaize** [comment]
That's nothing. I didn't notice that with negligence.

BUT,I have tried  this way and it has a problem.
If I set 'Close to the notification area‘ to yes and close the shell, the
next time I maximize the shell, it will still be styled in TOOLWINDOW and
looks like very strange. The reason is that the 'exStyle' cannot be
restored by ’OR' operation. So, I use the magic number in my pull request.

**Comment by digimezzo** [comment]
Wow, indeed. I didn't even notice that. Just curious, how did you find out about this magic number?
I'm now modifying the code to also ad the number to the ShowWindowInAltTab() function.

Thanks again for the help!

**Comment by Magentaize** [comment]
That's truly a magic~I noticed it in the Watch Window but I cannot recurrent. Anyway, it works so I add it. XD

**Comment by digimezzo** [comment]
Excellent :) I've added it in this commit: e350548fb498c9d95e7e28eef1c8159e32e9ade6

**Comment by Magentaize** [comment]
Umm, for a enhancement, only using `SetWindowLongPtr` may be a better choice. The original code in StackOverFlow to compare `IntPtr.Size == 4` seems useless and not recommended (ref from MSDN).

**Comment by digimezzo** [comment]
Excellent! That cleans it up. Done in commit 0c0465ad381d8f224d3655912532af7c58f4307c

**Pull request closed without merging**
