### PR TITLE
Implement set playback device #16.

### PR DESCRIPTION
**Pull request by Magentaize**
The code maybe mess, and I know there're much more logic should be considered. I'll improve it if you point them out. :)

### CODE REVIEW

**Comment by digimezzo** [comment]
I only had a quick look at the changes, and it looks  good. I can only think about 3 possible improvements:
1. Remember the selected audio device in the settings, and if on next start the selected devices is not available, use the default device.
2. Resuming playback when the audio device is changed during playback. I think the code in SetCurrentOutputDeviceAsync() is not optimal. 
3. Add an extra option in the combobox called "Default", which would play audio on the default windows audio device, if chosen.

I'm going to test this out a bit.

**Comment by Magentaize** [comment]
I have tried to replace soundOut instead of stopping and re-playing the track, however, after I instantiated  a new soundOut object and called Dispose() of the dated one, the current soundOut also be disposed after a few seconds. I think I should manually dispose it but don't know why. 
I'll pay more attention to it.

**Comment by digimezzo** [comment]
Sorry, I didn't get a chance to test this out yet, But, in CSCorePlayer line 308, RoutingOptions are being set. These make sure sound continues playing when the default audio device is changed. I'm not sure if this is sufficient to make sure playback continues when explicitly changing the audio device using your code though. I'll probably try this out during the weekend.

**Comment by Magentaize** [comment]
I known the reason. Due to the soundOut which was binded to SpectrumAnalyzer, I cannot directly dispose this soundOut, before dispose it, the player and spectrum analyzer must be disposed, but if I add a method to switch it explicitly, ISpectrumPlayer also must be modified. So, in my opinion, calling IPlayer.Stop() maybe a better chioce.

**Comment by digimezzo** [comment]
~~Please have a look at 5b11d47d70437307140c9c90f431a8a9d1421c0b. It switches the audio device without disposing soundOut. Thanks to the WASAPI RoutingOptions the switch occurs gracefully.
Now I'll try to add a "Default" option to the switch box, so the user can choose to always have the audio play on the default device which is selected in Windows.~~
Sorry, that doesn't work. I forgot to remove the code that performs the dispose. I'm searching further.

**Comment by digimezzo** [comment]
I've asked the author of CSCore if there is a possibility to gracefully switch the audio device without re-initializing SoundOut: [https://github.com/filoe/cscore/issues/235](https://github.com/filoe/cscore/issues/235)

**Comment by Magentaize** [comment]
I'm afraid that the audio device only can be switched by initialize a new instance. In # 124 of CSCore, the author says 

> It is technically not possible to change to device after WasapiCapture got initialized because the initialization process initializes the devices and sets up all native objects based on this device.

Since the input device cannot be changed, the output device ought to behave same.

**Comment by digimezzo** [comment]
You're probably right. Let's see what he has to say about it :). In the meantime I've slightly refined your code, and added a "Default" audio device. When you select "Default", Dopamine plays audio on the device which is the Windows default. When the default device changes, Dopamine follows the device.

**Comment by filoe** [comment]
You can change the device of an instance. But you need to initialize it again.

**Pull request merged**
